version: '3'

volumes:
  pgdata:

services:
  db:
    container_name: scalaDB
    image: postgres:14
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scala_db
      PGGSSENCMODE: disable
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - default