//Регистрация
POST localhost:8080/users
Content-Type: application/json

{
  "userName": "WUMBAch12332",
  "firstName": "San9",
  "lastName": "Kuz",
  "phone": "899123",
  "password": "qwerty",
}

###

//Авторизация
POST localhost:8080/users/login
Content-Type: application/json

{
  "userName": "WUMBAch123",
  "password": "qwerty"
}

###

//Получение списка пользователей (Admin only)
GET localhost:8080/users/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2ODY0MTgzODYsImlhdCI6MTY4NjA1ODM4NiwianRpIjoiNTk3ZWExMDIxNDM3ZTc0NGNkNzAwZmQ3YzJjODFkZTIifQ.ZPutaCcWmvoti74XTsVMWuUXltQKzuLnVul2FcrZpYI


###

//Поиск пользователя по нику (Admin only)
GET localhost:8080/users/WUMBAch123
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2ODY0MTgzODYsImlhdCI6MTY4NjA1ODM4NiwianRpIjoiNTk3ZWExMDIxNDM3ZTc0NGNkNzAwZmQ3YzJjODFkZTIifQ.ZPutaCcWmvoti74XTsVMWuUXltQKzuLnVul2FcrZpYI

###

//Удаление пользователя по нику (Admin only)
DELETE localhost:8080/users/WUMBAch
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2ODY0MTgzODYsImlhdCI6MTY4NjA1ODM4NiwianRpIjoiNTk3ZWExMDIxNDM3ZTc0NGNkNzAwZmQ3YzJjODFkZTIifQ.ZPutaCcWmvoti74XTsVMWuUXltQKzuLnVul2FcrZpYI


